export enum SystemEvents {
    "LOG" = "LOG",
    "ERROR" = "ERROR",
    "ASSET_LOADER" = "ASSET_LOADER",
    "OBJECT" = "OBJECT"
};

export enum AssetLoaderEvents {
    ASSETS_LOADED,
    ASSETS_INSTALLED,
    ASSETS_INSTALL_ERROR,
    ASSETS_LOAD_ERROR,
    ASSETS_UPDATED,
    ASSETS_START_UNINSTALL,
    ASSETS_START_INSTALL,
    CHECKING_FOR_UPDATE,
    ASSETS_INIT_START,
    ASSETS_INIT_END
}